import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="auth" content="Jasurbek Isokov" />
        <meta name="keyword" content="Next.js Best practice" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
