import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

import pic1 from "../public/images/course-2-1.jpg";
import pic2 from "../public/images/course-2-2.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="auth" content="Jasurbek Isokov" />
        <meta name="keyword" content="Next.js Best practice" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Home</h1>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </div>
      </main>
      <section>
        <Image
          src={pic1}
          width="400"
          style={{ marginRight: "20px", borderRadius: "10px" }}
        />
        <Image src={pic2} width="400" style={{ borderRadius: "10px" }} />
      </section>
    </div>
  );
}
